name: Build and Release

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on version tags like v1.0.0, v2.1.3, etc.

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'
        
    - name: Restore dependencies
      run: dotnet restore MouseKeyboardTracker.csproj
      
    - name: Build application
      run: dotnet build MouseKeyboardTracker.csproj --configuration Release --no-restore
      
    - name: Publish self-contained executable
      run: dotnet publish MouseKeyboardTracker.csproj --configuration Release --runtime win-x64 --self-contained true --output ./publish
      
    - name: Create release archive
      run: |
        cd publish
        7z a -tzip ../MouseKeyboardTracker-${{ github.ref_name }}-win-x64.zip *
        cd ..
      
    - name: Get release info
      id: release_info
      run: |
        echo "tag_name=${{ github.ref_name }}" >> $env:GITHUB_OUTPUT
        echo "release_name=MouseKeyboardTracker ${{ github.ref_name }}" >> $env:GITHUB_OUTPUT
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      with:
        name: ${{ steps.release_info.outputs.release_name }}
        tag_name: ${{ steps.release_info.outputs.tag_name }}
        draft: false
        prerelease: false
        generate_release_notes: true
        files: |
          MouseKeyboardTracker-${{ github.ref_name }}-win-x64.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
